version: "3.2"

services:
  back:
    environment:
    - VERTX_CONF=$VERTX_CONF
    build:
      context: .
      dockerfile: docker/Dockerfile.back
    ports:
      - "8090:8090"
  front:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    ports:
      - "8080:8080"
  auth:
    environment:
      - MAILPASS=$MAILPASS
    build:
      context: .
      dockerfile: docker/Dockerfile.auth
    ports:
      - "9999:9999"