jwt:
  secret: @jwt.secret@

server:
  port: 9999

spring:
  datasource:
    url: @postgresql.url@
    username: @postgresql.username@
    password: @postgresql.password@
    driverClassName: @postgresql.driver.name@
  mail:
    host: smtp.gmail.com
    port: 587
    username: kanbanflow.notification@gmail.com
#    password: pass this as environment variable or command line params
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  confirm:
    url: @email.app.url@

logging:
  path: ./logs
